### ISSUE TITLE
issue with the character sheet 

### ISSUE THREAD

**Issue by FallenWind77** [silvative/accessibility-enhancements#4]
Hello, i have an issue with the character sheet 
![image](https://github.com/silvative/accessibility-enhancements/assets/19285647/51364313-9df7-40d7-9b9e-e6b807e31daa)

I tried to uninstall and try on the clean world. Was the same

**Comment by FallenWind77** [comment]
I tried to delete the background image but there are still stiles remaining. Dunno how to fix it HALP
![image](https://github.com/silvative/accessibility-enhancements/assets/19285647/73e740f4-b6cb-485d-9918-31e16bd75273)

**Comment by silvative** [comment]
Ahh, sorry about this- it happens when the system changes their CSS classes so my selectors aren't specific enough or are no longer valid. I'll update them to keep up to date, and I think I might have to get a bit more crude so that my overrides are more robust.

**Comment by silvative** [comment]
Should be resolved in 0.3.1 !
